ALTER TABLE `admin_login_logs`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `admins`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `articles`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `assessment_parts`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `assessments`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `blogs`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `course_certificates`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `course_modules`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `course_tiers`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `courses`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `order_items`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `orders`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `pricing_tiers`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `products`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `questions`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `system_settings`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `temporary_download_links`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `test_answers`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `test_attempts`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `testimonials`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `user_enrollments`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `user_test_permissions`
  ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

ALTER TABLE `users`
  ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `created_by` INT(11) DEFAULT NULL,
  ADD COLUMN `updated_by` INT(11) DEFAULT NULL;

